export const FEEL_PRESETS = [
  {
    id: 'classical_legato',
    label: 'Legato Grid',
    styles: ['classical_film'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'classical_ostinato',
    label: 'Ostinato Push',
    styles: ['classical_film'],
    tags: ['tension', 'high_energy', 'on_grid'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.08,
  },
  {
    id: 'classical_waltz',
    label: 'Waltz Swing',
    styles: ['classical_film'],
    tags: ['dreamy', 'bright', 'swing'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'swing',
    timingIntensity: 0.14,
  },
  {
    id: 'classical_brisk',
    label: 'Brisk Bow',
    styles: ['classical_film'],
    tags: ['heroic', 'high_energy', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.02,
  },
  {
    id: 'jazz_lazy',
    label: 'Lazy Swing',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'low_energy', 'dreamy'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'swing',
    timingIntensity: 0.2,
  },
  {
    id: 'jazz_pocket',
    label: 'In the Pocket',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'swing'],
    rhythmGrid: '1/12',
    syncopation: 'anticipation',
    timingWarp: 'swing',
    timingIntensity: 0.18,
  },
  {
    id: 'jazz_ballad',
    label: 'Ballad Triplet',
    styles: ['jazz_blues_funk'],
    tags: ['dreamy', 'low_energy', 'tight_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'shuffle',
    timingIntensity: 0.12,
  },
  {
    id: 'funk_push',
    label: 'Funk Push',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'rock_on_grid',
    label: 'On-Grid Pulse',
    styles: ['rock_pop_metal'],
    tags: ['high_energy', 'bright', 'on_grid'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'rock_half_time',
    label: 'Half-Time Sway',
    styles: ['rock_pop_metal'],
    tags: ['dreamy', 'low_energy', 'dark'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.1,
  },
  {
    id: 'rock_drive',
    label: 'Drive Straight',
    styles: ['rock_pop_metal'],
    tags: ['heroic', 'high_energy', 'wide_register'],
    rhythmGrid: '1/16',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.02,
  },
  {
    id: 'rock_grit',
    label: 'Grit Swing',
    styles: ['rock_pop_metal'],
    tags: ['syncopated', 'dark', 'tight_register'],
    rhythmGrid: '1/12',
    syncopation: 'anticipation',
    timingWarp: 'shuffle',
    timingIntensity: 0.16,
  },
  {
    id: 'edm_groove',
    label: 'Club Groove',
    styles: ['edm_electronic'],
    tags: ['high_energy', 'on_grid', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.02,
  },
  {
    id: 'edm_hypnotic',
    label: 'Hypnotic Grid',
    styles: ['edm_electronic'],
    tags: ['tension', 'syncopated', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'none',
    timingIntensity: 0.06,
  },
  {
    id: 'edm_float',
    label: 'Floating',
    styles: ['edm_electronic'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.08,
  },
  {
    id: 'edm_tight',
    label: 'Tight Stabs',
    styles: ['edm_electronic'],
    tags: ['on_grid', 'high_energy', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.03,
  },
  {
    id: 'latin_sway',
    label: 'Swaying Clave',
    styles: ['latin_afrocuban'],
    tags: ['syncopated', 'swing', 'bright'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'swing',
    timingIntensity: 0.15,
  },
  {
    id: 'latin_drive',
    label: 'Driving Clave',
    styles: ['latin_afrocuban'],
    tags: ['high_energy', 'syncopated', 'percussive'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'latin_minor',
    label: 'Minor Flow',
    styles: ['latin_afrocuban'],
    tags: ['dark', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'shuffle',
    timingIntensity: 0.12,
  },
  {
    id: 'latin_ceremonial',
    label: 'Ceremonial March',
    styles: ['latin_afrocuban'],
    tags: ['tension', 'wide_register', 'syncopated'],
    rhythmGrid: '1/8',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.06,
  },
  {
    id: 'folk_simple',
    label: 'Simple Stride',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'stable', 'tight_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.03,
  },
  {
    id: 'folk_shuffle',
    label: 'Dusty Shuffle',
    styles: ['folk_country_bluegrass'],
    tags: ['dark', 'low_energy', 'swing'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.12,
  },
  {
    id: 'folk_drive',
    label: 'Bluegrass Drive',
    styles: ['folk_country_bluegrass'],
    tags: ['high_energy', 'syncopated', 'swing'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'folk_waltz',
    label: 'Waltz Brush',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'swing',
    timingIntensity: 0.1,
  },
  {
    id: 'legacy_default_feel',
    label: 'Legacy Default',
    styles: ['legacy'],
    tags: ['neutral'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0,
  },
];

export const FEEL_BY_ID = FEEL_PRESETS.reduce((acc, feel) => {
  acc[feel.id] = feel;
  return acc;
}, {});
