export const FEEL_PRESETS = [
  {
    id: 'classical_legato',
    label: 'Legato Grid',
    styles: ['classical_film'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'classical_ostinato',
    label: 'Ostinato Push',
    styles: ['classical_film'],
    tags: ['tension', 'high_energy', 'on_grid'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.08,
  },
  {
    id: 'classical_waltz',
    label: 'Waltz Swing',
    styles: ['classical_film'],
    tags: ['dreamy', 'bright', 'swing'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'swing',
    timingIntensity: 0.14,
  },
  {
    id: 'classical_brisk',
    label: 'Brisk Bow',
    styles: ['classical_film'],
    tags: ['heroic', 'high_energy', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.02,
  },
  {
    id: 'classical_swell',
    label: 'Swell Phrase',
    styles: ['classical_film'],
    tags: ['romantic', 'dreamy', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'none',
    timingIntensity: 0.1,
  },
  {
    id: 'classical_march',
    label: 'Marching Pulse',
    styles: ['classical_film'],
    tags: ['heroic', 'on_grid', 'tight_register'],
    rhythmGrid: '1/16',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.03,
  },
  {
    id: 'classical_chamber',
    label: 'Chamber Lilt',
    styles: ['classical_film'],
    tags: ['calm', 'low_energy', 'tight_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'swing',
    timingIntensity: 0.09,
  },
  {
    id: 'classical_staccato',
    label: 'Staccato Edge',
    styles: ['classical_film'],
    tags: ['tension', 'high_energy', 'tight_register'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.06,
  },
  {
    id: 'jazz_lazy',
    label: 'Lazy Swing',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'low_energy', 'dreamy'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'swing',
    timingIntensity: 0.2,
  },
  {
    id: 'jazz_pocket',
    label: 'In the Pocket',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'swing'],
    rhythmGrid: '1/12',
    syncopation: 'anticipation',
    timingWarp: 'swing',
    timingIntensity: 0.18,
  },
  {
    id: 'jazz_ballad',
    label: 'Ballad Triplet',
    styles: ['jazz_blues_funk'],
    tags: ['dreamy', 'low_energy', 'tight_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'shuffle',
    timingIntensity: 0.12,
  },
  {
    id: 'funk_push',
    label: 'Funk Push',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'jazz_noir_shuffle',
    label: 'Noir Shuffle',
    styles: ['jazz_blues_funk'],
    tags: ['dark', 'low_energy', 'swing'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.18,
  },
  {
    id: 'jazz_smooth',
    label: 'Smooth Lounge',
    styles: ['jazz_blues_funk'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'swing',
    timingIntensity: 0.08,
  },
  {
    id: 'jazz_fast_bop',
    label: 'Fast Bop',
    styles: ['jazz_blues_funk'],
    tags: ['high_energy', 'syncopated', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'swing',
    timingIntensity: 0.12,
  },
  {
    id: 'jazz_slow_blues',
    label: 'Slow Blues',
    styles: ['jazz_blues_funk'],
    tags: ['blue', 'low_energy', 'tight_register'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.14,
  },
  {
    id: 'rock_on_grid',
    label: 'On-Grid Pulse',
    styles: ['pop_rock'],
    tags: ['high_energy', 'bright', 'on_grid'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'rock_half_time',
    label: 'Half-Time Sway',
    styles: ['pop_rock'],
    tags: ['dreamy', 'low_energy', 'dark'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.1,
  },
  {
    id: 'rock_drive',
    label: 'Drive Straight',
    styles: ['pop_rock'],
    tags: ['heroic', 'high_energy', 'wide_register'],
    rhythmGrid: '1/16',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.02,
  },
  {
    id: 'rock_grit',
    label: 'Grit Swing',
    styles: ['pop_rock'],
    tags: ['syncopated', 'dark', 'tight_register'],
    rhythmGrid: '1/12',
    syncopation: 'anticipation',
    timingWarp: 'shuffle',
    timingIntensity: 0.16,
  },
  {
    id: 'rock_stomp',
    label: 'Stomp Clap',
    styles: ['pop_rock'],
    tags: ['high_energy', 'on_grid', 'tight_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.03,
  },
  {
    id: 'rock_airy',
    label: 'Airy Lift',
    styles: ['pop_rock'],
    tags: ['dreamy', 'wide_register', 'low_energy'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'none',
    timingIntensity: 0.08,
  },
  {
    id: 'pop_bounce',
    label: 'Pop Bounce',
    styles: ['pop_rock'],
    tags: ['bright', 'syncopated', 'high_energy'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'pop_midtempo',
    label: 'Midtempo Sway',
    styles: ['pop_rock'],
    tags: ['bright', 'low_energy', 'stable'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'shuffle',
    timingIntensity: 0.09,
  },
  {
    id: 'edm_groove',
    label: 'Club Groove',
    styles: ['edm_electronic'],
    tags: ['high_energy', 'on_grid', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.02,
  },
  {
    id: 'edm_hypnotic',
    label: 'Hypnotic Grid',
    styles: ['edm_electronic'],
    tags: ['tension', 'syncopated', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'none',
    timingIntensity: 0.06,
  },
  {
    id: 'edm_float',
    label: 'Floating',
    styles: ['edm_electronic'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.08,
  },
  {
    id: 'edm_tight',
    label: 'Tight Stabs',
    styles: ['edm_electronic'],
    tags: ['on_grid', 'high_energy', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.03,
  },
  {
    id: 'edm_riser',
    label: 'Riser Sweep',
    styles: ['edm_electronic'],
    tags: ['uplifting', 'wide_register', 'on_grid'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'edm_bounce',
    label: 'Bounce Grid',
    styles: ['edm_electronic'],
    tags: ['playful', 'syncopated', 'high_energy'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'edm_darkstep',
    label: 'Darkstep',
    styles: ['edm_electronic'],
    tags: ['dark', 'tension', 'on_grid'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'none',
    timingIntensity: 0.07,
  },
  {
    id: 'edm_chillstep',
    label: 'Chillstep',
    styles: ['edm_electronic'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'shuffle',
    timingIntensity: 0.1,
  },
  {
    id: 'latin_sway',
    label: 'Swaying Clave',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'swing', 'bright'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'swing',
    timingIntensity: 0.15,
  },
  {
    id: 'latin_drive',
    label: 'Driving Clave',
    styles: ['latin_afro_cuban'],
    tags: ['high_energy', 'syncopated', 'percussive'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'latin_minor',
    label: 'Minor Flow',
    styles: ['latin_afro_cuban'],
    tags: ['dark', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'shuffle',
    timingIntensity: 0.12,
  },
  {
    id: 'latin_ceremonial',
    label: 'Ceremonial March',
    styles: ['latin_afro_cuban'],
    tags: ['tension', 'wide_register', 'syncopated'],
    rhythmGrid: '1/8',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.06,
  },
  {
    id: 'latin_cha_cha',
    label: 'Cha-Cha Pulse',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'bright', 'playful'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'swing',
    timingIntensity: 0.14,
  },
  {
    id: 'latin_rumba_flow',
    label: 'Rumba Flow',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'bright', 'dance'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'latin_bolero_sway',
    label: 'Bolero Sway',
    styles: ['latin_afro_cuban'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.12,
  },
  {
    id: 'latin_fiesta',
    label: 'Fiesta Drive',
    styles: ['latin_afro_cuban'],
    tags: ['high_energy', 'percussive', 'syncopated'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'folk_simple',
    label: 'Simple Stride',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'stable', 'tight_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.03,
  },
  {
    id: 'folk_shuffle',
    label: 'Dusty Shuffle',
    styles: ['folk_country_bluegrass'],
    tags: ['dark', 'low_energy', 'swing'],
    rhythmGrid: '1/12',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.12,
  },
  {
    id: 'folk_drive',
    label: 'Bluegrass Drive',
    styles: ['folk_country_bluegrass'],
    tags: ['high_energy', 'syncopated', 'swing'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'folk_waltz',
    label: 'Waltz Brush',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'swing',
    timingIntensity: 0.1,
  },
  {
    id: 'folk_train_beat',
    label: 'Train Beat',
    styles: ['folk_country_bluegrass'],
    tags: ['on_grid', 'high_energy', 'tight_register'],
    rhythmGrid: '1/8',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0.04,
  },
  {
    id: 'folk_picker',
    label: 'Picker Swing',
    styles: ['folk_country_bluegrass'],
    tags: ['syncopated', 'swing', 'bright'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'swing',
    timingIntensity: 0.07,
  },
  {
    id: 'folk_storyteller',
    label: 'Storyteller',
    styles: ['folk_country_bluegrass'],
    tags: ['warm', 'low_energy', 'wide_register'],
    rhythmGrid: '1/8',
    syncopation: 'offbeat',
    timingWarp: 'shuffle',
    timingIntensity: 0.11,
  },
  {
    id: 'folk_lively_drive',
    label: 'Lively Drive',
    styles: ['folk_country_bluegrass'],
    tags: ['high_energy', 'syncopated', 'tight_register'],
    rhythmGrid: '1/16',
    syncopation: 'anticipation',
    timingWarp: 'none',
    timingIntensity: 0.05,
  },
  {
    id: 'legacy_default_feel',
    label: 'Legacy Default',
    styles: ['legacy'],
    tags: ['neutral'],
    rhythmGrid: '1/12',
    syncopation: 'none',
    timingWarp: 'none',
    timingIntensity: 0,
  },
];

export const FEEL_BY_ID = FEEL_PRESETS.reduce((acc, feel) => {
  acc[feel.id] = feel;
  return acc;
}, {});
