export const HARMONY_PROGRESSIONS = [
  // Classical / Film
  {
    id: 'classical_noble_cadence',
    label: 'Noble Cadence',
    styles: ['classical_film'],
    tags: ['heroic', 'bright', 'stable', 'wide_register'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable', 'bright'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush', 'dreamy'] },
    ],
  },
  {
    id: 'classical_wistful_minor',
    label: 'Wistful Minor',
    styles: ['classical_film'],
    tags: ['dreamy', 'dark', 'low_energy'],
    romanTemplate: 'i VI III VII',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: 'Add 7ths', tags: ['dreamy'] },
    ],
  },
  {
    id: 'classical_suspense_steps',
    label: 'Suspense Steps',
    styles: ['classical_film'],
    tags: ['tension', 'dark', 'tight_register'],
    romanTemplate: 'i ii° V i',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['tension'] },
      { id: '9ths_soft', label: 'Add 9ths (Soft)', tags: ['lush', 'dreamy'] },
    ],
  },
  {
    id: 'classical_ostinato',
    label: 'Ostinato Pulse',
    styles: ['classical_film'],
    tags: ['tension', 'high_energy', 'dark'],
    romanTemplate: 'i v i v',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['driving'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'classical_storybook',
    label: 'Storybook Resolve',
    styles: ['classical_film'],
    tags: ['bright', 'stable', 'wide_register'],
    romanTemplate: 'IV V I I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'classical_romantic_swell',
    label: 'Romantic Swell',
    styles: ['classical_film'],
    tags: ['romantic', 'bright', 'wide_register'],
    romanTemplate: 'I iii IV V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush', 'dreamy'] },
    ],
  },
  {
    id: 'classical_mournful',
    label: 'Mournful Descent',
    styles: ['classical_film'],
    tags: ['dark', 'low_energy', 'tension'],
    romanTemplate: 'i VI iv V',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['somber'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'classical_epic_lift',
    label: 'Epic Lift',
    styles: ['classical_film'],
    tags: ['heroic', 'high_energy', 'wide_register'],
    romanTemplate: 'IV I V vi',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['heroic'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'classical_pastoral',
    label: 'Pastoral Light',
    styles: ['classical_film'],
    tags: ['calm', 'bright', 'stable'],
    romanTemplate: 'I IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'classical_twilight',
    label: 'Twilight Resolve',
    styles: ['classical_film'],
    tags: ['dreamy', 'romantic', 'wide_register'],
    romanTemplate: 'vi ii V I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['gentle'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'classical_ominous_pedal',
    label: 'Ominous Pedal',
    styles: ['classical_film'],
    tags: ['tension', 'dark', 'tight_register'],
    romanTemplate: 'i bII i V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['tension'] },
      { id: 'sparse', label: 'Sparse', tags: ['space'] },
    ],
  },
  {
    id: 'classical_chase',
    label: 'Chase Sequence',
    styles: ['classical_film'],
    tags: ['high_energy', 'tension', 'tight_register'],
    romanTemplate: 'i bVII IV V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['drive'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  // Jazz / Blues / Funk
  {
    id: 'jazz_ii_v_i',
    label: 'ii–V–I',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'bright', 'stable'],
    romanTemplate: 'ii V I',
    defaultLengthBars: 3,
    constraints: ['major'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy', 'swing'] },
      { id: '9ths_soft', label: '9ths (Soft)', tags: ['lush', 'dreamy'] },
    ],
  },
  {
    id: 'jazz_turnaround',
    label: 'Turnaround',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'bright', 'syncopated'],
    romanTemplate: 'I vi ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
      { id: 'triads', label: 'Triads', tags: ['simple'] },
    ],
  },
  {
    id: 'jazz_blues_form',
    label: 'Blues Changes',
    styles: ['jazz_blues_funk'],
    tags: ['dark', 'swing', 'tight_register'],
    romanTemplate: 'I IV I V',
    defaultLengthBars: 4,
    constraints: ['major', 'modal'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['blue'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'jazz_minor_vamp',
    label: 'Minor Vamp',
    styles: ['jazz_blues_funk'],
    tags: ['dark', 'low_energy', 'swing'],
    romanTemplate: 'i bVII bVI V',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['blue'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'jazz_call_response',
    label: 'Call & Response',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'swing'],
    romanTemplate: 'ii V ii V',
    defaultLengthBars: 4,
    constraints: ['major', 'modal'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'jazz_rhythm_changes',
    label: 'Rhythm Changes',
    styles: ['jazz_blues_funk'],
    tags: ['bright', 'swing', 'high_energy'],
    romanTemplate: 'I vi ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'jazz_minor_turnaround',
    label: 'Minor Turnaround',
    styles: ['jazz_blues_funk'],
    tags: ['dark', 'swing', 'tight_register'],
    romanTemplate: 'i VI ii° V',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['blue'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'jazz_funk_vamp',
    label: 'Funk Vamp',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'tight_register'],
    romanTemplate: 'i iv i iv',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['groove'] },
      { id: 'sparse', label: 'Sparse', tags: ['space'] },
    ],
  },
  {
    id: 'jazz_soulful',
    label: 'Soulful Walk',
    styles: ['jazz_blues_funk'],
    tags: ['bright', 'swing', 'stable'],
    romanTemplate: 'I IV ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'jazz_noir_walk',
    label: 'Noir Walk',
    styles: ['jazz_blues_funk'],
    tags: ['dark', 'tension', 'swing'],
    romanTemplate: 'i bVII bVI V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['blue'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'jazz_modal_dorian',
    label: 'Dorian Drift',
    styles: ['jazz_blues_funk'],
    tags: ['dreamy', 'low_energy', 'swing'],
    romanTemplate: 'i IV i V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['modal'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'jazz_shuffle_riff',
    label: 'Shuffle Riff',
    styles: ['jazz_blues_funk'],
    tags: ['high_energy', 'syncopated', 'swing'],
    romanTemplate: 'I bVII IV I',
    defaultLengthBars: 4,
    constraints: ['major', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['drive'] },
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
    ],
  },
  // Rock / Pop / Metal
  {
    id: 'rock_anthem',
    label: 'Anthem Hook',
    styles: ['pop_rock'],
    tags: ['bright', 'heroic', 'high_energy'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  {
    id: 'rock_melancholy',
    label: 'Melancholy Loop',
    styles: ['pop_rock'],
    tags: ['dreamy', 'low_energy', 'dark'],
    romanTemplate: 'vi IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'rock_minor_power',
    label: 'Minor Power',
    styles: ['pop_rock'],
    tags: ['dark', 'high_energy', 'tight_register'],
    romanTemplate: 'i bVI bVII i',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'power', label: 'Power', tags: ['high_energy'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'rock_suspense',
    label: 'Suspense Rise',
    styles: ['pop_rock'],
    tags: ['tension', 'dark', 'on_grid'],
    romanTemplate: 'i iv V i',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['tension'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'rock_drive',
    label: 'Drive',
    styles: ['pop_rock'],
    tags: ['high_energy', 'bright', 'heroic'],
    romanTemplate: 'I IV V I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  {
    id: 'pop_bright_hook',
    label: 'Bright Hook',
    styles: ['pop_rock'],
    tags: ['bright', 'high_energy', 'wide_register'],
    romanTemplate: 'I IV vi V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'pop_bittersweet',
    label: 'Bittersweet Turn',
    styles: ['pop_rock'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    romanTemplate: 'vi IV I iii',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['gentle'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'pop_drive',
    label: 'Driving Loop',
    styles: ['pop_rock'],
    tags: ['high_energy', 'on_grid', 'tight_register'],
    romanTemplate: 'I V IV V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['drive'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  {
    id: 'rock_grit_loop',
    label: 'Grit Loop',
    styles: ['pop_rock'],
    tags: ['dark', 'high_energy', 'tight_register'],
    romanTemplate: 'i bVII IV i',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'power', label: 'Power', tags: ['drive'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'rock_power_chorus',
    label: 'Power Chorus',
    styles: ['pop_rock'],
    tags: ['heroic', 'bright', 'high_energy'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'power', label: 'Power', tags: ['high_energy'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'pop_sparkle',
    label: 'Sparkle Lift',
    styles: ['pop_rock'],
    tags: ['bright', 'stable', 'wide_register'],
    romanTemplate: 'I ii IV V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['sparkle'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'rock_noir',
    label: 'Noir Descent',
    styles: ['pop_rock'],
    tags: ['dark', 'tension', 'low_energy'],
    romanTemplate: 'i iv bVII VI',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['moody'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  // EDM / Electronic
  {
    id: 'edm_euphoric',
    label: 'Euphoric Lift',
    styles: ['edm_electronic'],
    tags: ['bright', 'high_energy', 'on_grid'],
    romanTemplate: 'vi IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_dark_drive',
    label: 'Dark Drive',
    styles: ['edm_electronic'],
    tags: ['dark', 'tension', 'high_energy'],
    romanTemplate: 'i bVII bVI V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['tight_register'] },
    ],
  },
  {
    id: 'edm_chillwave',
    label: 'Chillwave',
    styles: ['edm_electronic'],
    tags: ['dreamy', 'low_energy', 'on_grid'],
    romanTemplate: 'I V vi iii',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_hypnotic',
    label: 'Hypnotic Loop',
    styles: ['edm_electronic'],
    tags: ['on_grid', 'syncopated', 'tension'],
    romanTemplate: 'i v i v',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'edm_anthemic',
    label: 'Anthemic Rise',
    styles: ['edm_electronic'],
    tags: ['bright', 'heroic', 'wide_register'],
    romanTemplate: 'I V vi V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_uplift',
    label: 'Uplift Surge',
    styles: ['edm_electronic'],
    tags: ['bright', 'high_energy', 'on_grid'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_playful_bounce',
    label: 'Playful Bounce',
    styles: ['edm_electronic'],
    tags: ['bright', 'syncopated', 'high_energy'],
    romanTemplate: 'I vi IV V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['playful'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_techno_vamp',
    label: 'Techno Vamp',
    styles: ['edm_electronic'],
    tags: ['dark', 'on_grid', 'tension'],
    romanTemplate: 'i v i v',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['steady'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'edm_rainy_minor',
    label: 'Rainy Minor',
    styles: ['edm_electronic'],
    tags: ['dark', 'dreamy', 'low_energy'],
    romanTemplate: 'i VI III VII',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['moody'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_glow',
    label: 'Glow Lift',
    styles: ['edm_electronic'],
    tags: ['bright', 'wide_register', 'on_grid'],
    romanTemplate: 'IV I V vi',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_pulse',
    label: 'Pulse Drift',
    styles: ['edm_electronic'],
    tags: ['dark', 'tension', 'on_grid'],
    romanTemplate: 'i bVII VI bVII',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['steady'] },
      { id: 'sparse', label: 'Sparse', tags: ['space'] },
    ],
  },
  {
    id: 'edm_sunrise',
    label: 'Sunrise Major',
    styles: ['edm_electronic'],
    tags: ['uplifting', 'bright', 'wide_register'],
    romanTemplate: 'I IV V I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  // Latin / Afro-Cuban
  {
    id: 'latin_sunny_son',
    label: 'Sunny Son',
    styles: ['latin_afro_cuban'],
    tags: ['bright', 'syncopated', 'swing'],
    romanTemplate: 'I V ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['light'] },
    ],
  },
  {
    id: 'latin_tumbao',
    label: 'Minor Tumbao',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'dark', 'percussive'],
    romanTemplate: 'i V bVII IV',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['groove'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'latin_cadence',
    label: 'Cadence Walk',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'bright', 'wide_register'],
    romanTemplate: 'ii V I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
    ],
  },
  {
    id: 'latin_drive',
    label: 'Driving Song',
    styles: ['latin_afro_cuban'],
    tags: ['high_energy', 'syncopated', 'percussive'],
    romanTemplate: 'i IV V i',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['drive'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  {
    id: 'latin_ceremonial',
    label: 'Ceremonial Steps',
    styles: ['latin_afro_cuban'],
    tags: ['tension', 'wide_register', 'syncopated'],
    romanTemplate: 'i bVII IV V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['tension'] },
      { id: 'sparse', label: 'Sparse', tags: ['space'] },
    ],
  },
  {
    id: 'latin_salsa_turn',
    label: 'Salsa Turn',
    styles: ['latin_afro_cuban'],
    tags: ['bright', 'syncopated', 'high_energy'],
    romanTemplate: 'I IV V IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['dance'] },
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
    ],
  },
  {
    id: 'latin_bolero',
    label: 'Bolero Bloom',
    styles: ['latin_afro_cuban'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    romanTemplate: 'i iv V i',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['romantic'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'latin_rumba',
    label: 'Rumba Walk',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'bright', 'dance'],
    romanTemplate: 'I V ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['dance'] },
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
    ],
  },
  {
    id: 'latin_fiery',
    label: 'Fiery Steps',
    styles: ['latin_afro_cuban'],
    tags: ['high_energy', 'percussive', 'syncopated'],
    romanTemplate: 'i bVII IV V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'power', label: 'Power', tags: ['drive'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'latin_suave',
    label: 'Suave Drift',
    styles: ['latin_afro_cuban'],
    tags: ['low_energy', 'syncopated', 'wide_register'],
    romanTemplate: 'ii V I vi',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['smooth'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'latin_paseo',
    label: 'Paseo Pulse',
    styles: ['latin_afro_cuban'],
    tags: ['bright', 'stable', 'dance'],
    romanTemplate: 'I V I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['steady'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'latin_cha_cha',
    label: 'Cha-Cha Loop',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'bright', 'playful'],
    romanTemplate: 'I vi ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['playful'] },
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
    ],
  },
  // Folk / Country / Bluegrass
  {
    id: 'folk_circle',
    label: 'Circle of Home',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'stable', 'acoustic'],
    romanTemplate: 'I IV V I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'folk_heartbreak',
    label: 'Heartbreak Loop',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'dark'],
    romanTemplate: 'vi IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'bluegrass_drive',
    label: 'Bluegrass Drive',
    styles: ['folk_country_bluegrass'],
    tags: ['high_energy', 'syncopated', 'swing'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'power', label: 'Power', tags: ['drive'] },
    ],
  },
  {
    id: 'country_two_step',
    label: 'Two-Step',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'on_grid', 'stable'],
    romanTemplate: 'I V I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['simple'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'folk_minor_ballad',
    label: 'Minor Ballad',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    romanTemplate: 'i VII VI VII',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'folk_warm_home',
    label: 'Warm Home',
    styles: ['folk_country_bluegrass'],
    tags: ['warm', 'stable', 'bright'],
    romanTemplate: 'I IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'folk_lonesome',
    label: 'Lonesome Trail',
    styles: ['folk_country_bluegrass'],
    tags: ['dark', 'low_energy', 'wide_register'],
    romanTemplate: 'i VII VI VII',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['moody'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'folk_nostalgic',
    label: 'Nostalgic Drift',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    romanTemplate: 'I vi IV V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['gentle'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'folk_lively',
    label: 'Lively Porch',
    styles: ['folk_country_bluegrass'],
    tags: ['high_energy', 'bright', 'tight_register'],
    romanTemplate: 'I V IV I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['drive'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  {
    id: 'folk_train',
    label: 'Train Wheels',
    styles: ['folk_country_bluegrass'],
    tags: ['on_grid', 'high_energy', 'tight_register'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['drive'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'folk_moonlight',
    label: 'Moonlight Waltz',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    romanTemplate: 'vi IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['gentle'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'folk_gospel',
    label: 'Gospel Walk',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'stable', 'wide_register'],
    romanTemplate: 'I IV ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  // Legacy fallbacks
  {
    id: 'legacy_pop',
    label: 'Legacy Pop',
    styles: ['legacy'],
    tags: ['neutral'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
];

export const HARMONY_BY_ID = HARMONY_PROGRESSIONS.reduce((acc, progression) => {
  acc[progression.id] = progression;
  return acc;
}, {});
