export const HARMONY_PROGRESSIONS = [
  // Classical / Film
  {
    id: 'classical_noble_cadence',
    label: 'Noble Cadence',
    styles: ['classical_film'],
    tags: ['heroic', 'bright', 'stable', 'wide_register'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable', 'bright'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush', 'dreamy'] },
    ],
  },
  {
    id: 'classical_wistful_minor',
    label: 'Wistful Minor',
    styles: ['classical_film'],
    tags: ['dreamy', 'dark', 'low_energy'],
    romanTemplate: 'i VI III VII',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: 'Add 7ths', tags: ['dreamy'] },
    ],
  },
  {
    id: 'classical_suspense_steps',
    label: 'Suspense Steps',
    styles: ['classical_film'],
    tags: ['tension', 'dark', 'tight_register'],
    romanTemplate: 'i ii° V i',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['tension'] },
      { id: '9ths_soft', label: 'Add 9ths (Soft)', tags: ['lush', 'dreamy'] },
    ],
  },
  {
    id: 'classical_ostinato',
    label: 'Ostinato Pulse',
    styles: ['classical_film'],
    tags: ['tension', 'high_energy', 'dark'],
    romanTemplate: 'i v i v',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['driving'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'classical_storybook',
    label: 'Storybook Resolve',
    styles: ['classical_film'],
    tags: ['bright', 'stable', 'wide_register'],
    romanTemplate: 'IV V I I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: 'Add 7ths', tags: ['lush'] },
    ],
  },
  // Jazz / Blues / Funk
  {
    id: 'jazz_ii_v_i',
    label: 'ii–V–I',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'bright', 'stable'],
    romanTemplate: 'ii V I',
    defaultLengthBars: 3,
    constraints: ['major'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy', 'swing'] },
      { id: '9ths_soft', label: '9ths (Soft)', tags: ['lush', 'dreamy'] },
    ],
  },
  {
    id: 'jazz_turnaround',
    label: 'Turnaround',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'bright', 'syncopated'],
    romanTemplate: 'I vi ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
      { id: 'triads', label: 'Triads', tags: ['simple'] },
    ],
  },
  {
    id: 'jazz_blues_form',
    label: 'Blues Changes',
    styles: ['jazz_blues_funk'],
    tags: ['dark', 'swing', 'tight_register'],
    romanTemplate: 'I IV I V',
    defaultLengthBars: 4,
    constraints: ['major', 'modal'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['blue'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'jazz_minor_vamp',
    label: 'Minor Vamp',
    styles: ['jazz_blues_funk'],
    tags: ['dark', 'low_energy', 'swing'],
    romanTemplate: 'i bVII bVI V',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['blue'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'jazz_call_response',
    label: 'Call & Response',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'swing'],
    romanTemplate: 'ii V ii V',
    defaultLengthBars: 4,
    constraints: ['major', 'modal'],
    variants: [
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  // Rock / Pop / Metal
  {
    id: 'rock_anthem',
    label: 'Anthem Hook',
    styles: ['rock_pop_metal'],
    tags: ['bright', 'heroic', 'high_energy'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  {
    id: 'rock_melancholy',
    label: 'Melancholy Loop',
    styles: ['rock_pop_metal'],
    tags: ['dreamy', 'low_energy', 'dark'],
    romanTemplate: 'vi IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'rock_minor_power',
    label: 'Minor Power',
    styles: ['rock_pop_metal'],
    tags: ['dark', 'high_energy', 'tight_register'],
    romanTemplate: 'i bVI bVII i',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'power', label: 'Power', tags: ['high_energy'] },
      { id: 'triads', label: 'Triads', tags: ['stable'] },
    ],
  },
  {
    id: 'rock_suspense',
    label: 'Suspense Rise',
    styles: ['rock_pop_metal'],
    tags: ['tension', 'dark', 'on_grid'],
    romanTemplate: 'i iv V i',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['tension'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'rock_drive',
    label: 'Drive',
    styles: ['rock_pop_metal'],
    tags: ['high_energy', 'bright', 'heroic'],
    romanTemplate: 'I IV V I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  // EDM / Electronic
  {
    id: 'edm_euphoric',
    label: 'Euphoric Lift',
    styles: ['edm_electronic'],
    tags: ['bright', 'high_energy', 'on_grid'],
    romanTemplate: 'vi IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_dark_drive',
    label: 'Dark Drive',
    styles: ['edm_electronic'],
    tags: ['dark', 'tension', 'high_energy'],
    romanTemplate: 'i bVII bVI V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['tight_register'] },
    ],
  },
  {
    id: 'edm_chillwave',
    label: 'Chillwave',
    styles: ['edm_electronic'],
    tags: ['dreamy', 'low_energy', 'on_grid'],
    romanTemplate: 'I V vi iii',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'edm_hypnotic',
    label: 'Hypnotic Loop',
    styles: ['edm_electronic'],
    tags: ['on_grid', 'syncopated', 'tension'],
    romanTemplate: 'i v i v',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'edm_anthemic',
    label: 'Anthemic Rise',
    styles: ['edm_electronic'],
    tags: ['bright', 'heroic', 'wide_register'],
    romanTemplate: 'I V vi V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  // Latin / Afro-Cuban
  {
    id: 'latin_sunny_son',
    label: 'Sunny Son',
    styles: ['latin_afrocuban'],
    tags: ['bright', 'syncopated', 'swing'],
    romanTemplate: 'I V ii V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['light'] },
    ],
  },
  {
    id: 'latin_tumbao',
    label: 'Minor Tumbao',
    styles: ['latin_afrocuban'],
    tags: ['syncopated', 'dark', 'percussive'],
    romanTemplate: 'i V bVII IV',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['groove'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'latin_cadence',
    label: 'Cadence Walk',
    styles: ['latin_afrocuban'],
    tags: ['syncopated', 'bright', 'wide_register'],
    romanTemplate: 'ii V I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['jazzy'] },
    ],
  },
  {
    id: 'latin_drive',
    label: 'Driving Song',
    styles: ['latin_afrocuban'],
    tags: ['high_energy', 'syncopated', 'percussive'],
    romanTemplate: 'i IV V i',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['drive'] },
      { id: 'power', label: 'Power', tags: ['high_energy'] },
    ],
  },
  {
    id: 'latin_ceremonial',
    label: 'Ceremonial Steps',
    styles: ['latin_afrocuban'],
    tags: ['tension', 'wide_register', 'syncopated'],
    romanTemplate: 'i bVII IV V',
    defaultLengthBars: 4,
    constraints: ['minor', 'modal'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['tension'] },
      { id: 'sparse', label: 'Sparse', tags: ['space'] },
    ],
  },
  // Folk / Country / Bluegrass
  {
    id: 'folk_circle',
    label: 'Circle of Home',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'stable', 'acoustic'],
    romanTemplate: 'I IV V I',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'folk_heartbreak',
    label: 'Heartbreak Loop',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'dark'],
    romanTemplate: 'vi IV I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  {
    id: 'bluegrass_drive',
    label: 'Bluegrass Drive',
    styles: ['folk_country_bluegrass'],
    tags: ['high_energy', 'syncopated', 'swing'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: 'power', label: 'Power', tags: ['drive'] },
    ],
  },
  {
    id: 'country_two_step',
    label: 'Two-Step',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'on_grid', 'stable'],
    romanTemplate: 'I V I V',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['simple'] },
      { id: 'sparse', label: 'Sparse', tags: ['low_energy'] },
    ],
  },
  {
    id: 'folk_minor_ballad',
    label: 'Minor Ballad',
    styles: ['folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    romanTemplate: 'i VII VI VII',
    defaultLengthBars: 4,
    constraints: ['minor'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
  // Legacy fallbacks
  {
    id: 'legacy_pop',
    label: 'Legacy Pop',
    styles: ['legacy'],
    tags: ['neutral'],
    romanTemplate: 'I V vi IV',
    defaultLengthBars: 4,
    constraints: ['major'],
    variants: [
      { id: 'triads', label: 'Triads', tags: ['stable'] },
      { id: '7ths', label: '7ths', tags: ['lush'] },
    ],
  },
];

export const HARMONY_BY_ID = HARMONY_PROGRESSIONS.reduce((acc, progression) => {
  acc[progression.id] = progression;
  return acc;
}, {});
