export const INSTRUMENT_SUGGESTIONS = [
  { id: 'cine_strings', label: 'Cinematic Strings', styles: ['classical_film'], tags: ['dreamy', 'wide_register', 'bright'], instrumentPreset: 'gm:0:48' },
  { id: 'cine_piano', label: 'Concert Piano', styles: ['classical_film'], tags: ['stable', 'bright'], instrumentPreset: 'gm:0:0' },
  { id: 'cine_brass', label: 'Heroic Brass', styles: ['classical_film'], tags: ['heroic', 'high_energy'], instrumentPreset: 'gm:0:61' },
  { id: 'cine_harp', label: 'Harp', styles: ['classical_film'], tags: ['romantic', 'dreamy'], instrumentPreset: 'gm:0:46' },
  { id: 'cine_choir', label: 'Choir', styles: ['classical_film'], tags: ['wide_register', 'lush'], instrumentPreset: 'gm:0:52' },
  { id: 'cine_flute', label: 'Flute Solo', styles: ['classical_film'], tags: ['bright', 'airy'], instrumentPreset: 'gm:0:73' },
  { id: 'cine_oboe', label: 'Oboe', styles: ['classical_film'], tags: ['warm', 'stable'], instrumentPreset: 'gm:0:68' },
  { id: 'cine_celesta', label: 'Celesta', styles: ['classical_film'], tags: ['sparkle', 'bright'], instrumentPreset: 'gm:0:8' },
  { id: 'cine_bells', label: 'Bell Choir', styles: ['classical_film'], tags: ['wide_register', 'bright'], instrumentPreset: 'gm:0:14' },
  { id: 'cine_bassoon', label: 'Bassoon', styles: ['classical_film'], tags: ['dark', 'stable'], instrumentPreset: 'gm:0:70' },

  { id: 'jazz_piano', label: 'Jazz Piano', styles: ['jazz_blues_funk'], tags: ['swing', 'bright'], instrumentPreset: 'gm:0:2' },
  { id: 'jazz_guitar', label: 'Hollowbody Guitar', styles: ['jazz_blues_funk'], tags: ['warm', 'dreamy'], instrumentPreset: 'gm:0:26' },
  { id: 'funk_ep', label: 'Funk EP', styles: ['jazz_blues_funk'], tags: ['high_energy', 'syncopated'], instrumentPreset: 'gm:0:4' },
  { id: 'jazz_sax', label: 'Tenor Sax', styles: ['jazz_blues_funk'], tags: ['smoky', 'warm'], instrumentPreset: 'gm:0:66' },
  { id: 'jazz_trumpet', label: 'Muted Trumpet', styles: ['jazz_blues_funk'], tags: ['bright', 'swing'], instrumentPreset: 'gm:0:59' },
  { id: 'jazz_bass', label: 'Upright Bass', styles: ['jazz_blues_funk'], tags: ['tight_register', 'stable'], instrumentPreset: 'gm:0:32' },
  { id: 'jazz_organ', label: 'Jazz Organ', styles: ['jazz_blues_funk'], tags: ['warm', 'steady'], instrumentPreset: 'gm:0:19' },
  { id: 'jazz_vibes', label: 'Vibraphone', styles: ['jazz_blues_funk'], tags: ['dreamy', 'bright'], instrumentPreset: 'gm:0:11' },
  { id: 'jazz_clarinet', label: 'Clarinet', styles: ['jazz_blues_funk'], tags: ['smooth', 'warm'], instrumentPreset: 'gm:0:71' },
  { id: 'jazz_trombone', label: 'Trombone', styles: ['jazz_blues_funk'], tags: ['warm', 'wide_register'], instrumentPreset: 'gm:0:57' },

  { id: 'rock_stack', label: 'Stacked Guitar', styles: ['pop_rock'], tags: ['high_energy', 'heroic'], instrumentPreset: 'gm:0:29' },
  { id: 'rock_clean', label: 'Clean Guitar', styles: ['pop_rock'], tags: ['bright', 'stable'], instrumentPreset: 'gm:0:27' },
  { id: 'rock_synth', label: 'Pad Synth', styles: ['pop_rock'], tags: ['dreamy', 'wide_register'], instrumentPreset: 'gm:0:88' },
  { id: 'pop_piano', label: 'Pop Piano', styles: ['pop_rock'], tags: ['bright', 'stable'], instrumentPreset: 'gm:0:0' },
  { id: 'pop_synth_lead', label: 'Synth Lead', styles: ['pop_rock'], tags: ['bright', 'high_energy'], instrumentPreset: 'gm:0:80' },
  { id: 'pop_strings', label: 'Pop Strings', styles: ['pop_rock'], tags: ['wide_register', 'dreamy'], instrumentPreset: 'gm:0:48' },
  { id: 'pop_bass', label: 'Electric Bass', styles: ['pop_rock'], tags: ['tight_register', 'drive'], instrumentPreset: 'gm:0:34' },
  { id: 'pop_pluck', label: 'Pop Pluck', styles: ['pop_rock'], tags: ['bright', 'on_grid'], instrumentPreset: 'gm:0:82' },
  { id: 'pop_pad', label: 'Shimmer Pad', styles: ['pop_rock'], tags: ['dreamy', 'wide_register'], instrumentPreset: 'gm:0:89' },
  { id: 'pop_chime', label: 'Chime Bells', styles: ['pop_rock'], tags: ['sparkle', 'bright'], instrumentPreset: 'gm:0:9' },

  { id: 'edm_pluck', label: 'EDM Pluck', styles: ['edm_electronic'], tags: ['bright', 'on_grid'], instrumentPreset: 'gm:0:82' },
  { id: 'edm_pad', label: 'Wide Pad', styles: ['edm_electronic'], tags: ['dreamy', 'wide_register'], instrumentPreset: 'gm:0:89' },
  { id: 'edm_bass', label: 'Sub Bass', styles: ['edm_electronic'], tags: ['dark', 'tension'], instrumentPreset: 'gm:0:38' },
  { id: 'edm_lead', label: 'EDM Lead', styles: ['edm_electronic'], tags: ['bright', 'high_energy'], instrumentPreset: 'gm:0:81' },
  { id: 'edm_chord', label: 'Chord Stabs', styles: ['edm_electronic'], tags: ['on_grid', 'bright'], instrumentPreset: 'gm:0:87' },
  { id: 'edm_bell', label: 'Digital Bells', styles: ['edm_electronic'], tags: ['sparkle', 'wide_register'], instrumentPreset: 'gm:0:98' },
  { id: 'edm_fx', label: 'FX Sweep', styles: ['edm_electronic'], tags: ['tension', 'wide_register'], instrumentPreset: 'gm:0:97' },
  { id: 'edm_organ', label: 'Tech Organ', styles: ['edm_electronic'], tags: ['on_grid', 'steady'], instrumentPreset: 'gm:0:16' },
  { id: 'edm_strings', label: 'Synth Strings', styles: ['edm_electronic'], tags: ['dreamy', 'wide_register'], instrumentPreset: 'gm:0:50' },
  { id: 'edm_pluck_glass', label: 'Glass Pluck', styles: ['edm_electronic'], tags: ['bright', 'playful'], instrumentPreset: 'gm:0:84' },

  { id: 'latin_piano', label: 'Rhythm Piano', styles: ['latin_afro_cuban'], tags: ['syncopated', 'bright'], instrumentPreset: 'gm:0:0' },
  { id: 'latin_steel', label: 'Steel Drums', styles: ['latin_afro_cuban'], tags: ['bright', 'percussive'], instrumentPreset: 'gm:0:114' },
  { id: 'latin_brass', label: 'Brass Section', styles: ['latin_afro_cuban'], tags: ['high_energy', 'wide_register'], instrumentPreset: 'gm:0:61' },
  { id: 'latin_guitar', label: 'Nylon Guitar', styles: ['latin_afro_cuban'], tags: ['warm', 'bright'], instrumentPreset: 'gm:0:24' },
  { id: 'latin_bass', label: 'Latin Bass', styles: ['latin_afro_cuban'], tags: ['tight_register', 'stable'], instrumentPreset: 'gm:0:33' },
  { id: 'latin_flute', label: 'Latin Flute', styles: ['latin_afro_cuban'], tags: ['airy', 'bright'], instrumentPreset: 'gm:0:73' },
  { id: 'latin_marimba', label: 'Marimba', styles: ['latin_afro_cuban'], tags: ['percussive', 'bright'], instrumentPreset: 'gm:0:12' },
  { id: 'latin_accordion', label: 'Accordion', styles: ['latin_afro_cuban'], tags: ['warm', 'wide_register'], instrumentPreset: 'gm:0:21' },
  { id: 'latin_trumpet', label: 'Trumpet', styles: ['latin_afro_cuban'], tags: ['bright', 'high_energy'], instrumentPreset: 'gm:0:56' },
  { id: 'latin_vibes', label: 'Latin Vibes', styles: ['latin_afro_cuban'], tags: ['dreamy', 'bright'], instrumentPreset: 'gm:0:11' },

  { id: 'folk_acoustic', label: 'Acoustic Guitar', styles: ['folk_country_bluegrass'], tags: ['bright', 'stable'], instrumentPreset: 'gm:0:25' },
  { id: 'folk_banjo', label: 'Banjo', styles: ['folk_country_bluegrass'], tags: ['tight_register', 'swing'], instrumentPreset: 'gm:0:105' },
  { id: 'folk_dulcimer', label: 'Dulcimer', styles: ['folk_country_bluegrass'], tags: ['dreamy', 'low_energy'], instrumentPreset: 'gm:0:15' },
  { id: 'folk_fiddle', label: 'Fiddle', styles: ['folk_country_bluegrass'], tags: ['bright', 'lively'], instrumentPreset: 'gm:0:40' },
  { id: 'folk_mandolin', label: 'Mandolin', styles: ['folk_country_bluegrass'], tags: ['tight_register', 'bright'], instrumentPreset: 'gm:0:24' },
  { id: 'folk_harmonica', label: 'Harmonica', styles: ['folk_country_bluegrass'], tags: ['warm', 'lonesome'], instrumentPreset: 'gm:0:22' },
  { id: 'folk_piano', label: 'Honky Tonk', styles: ['folk_country_bluegrass'], tags: ['bright', 'stable'], instrumentPreset: 'gm:0:3' },
  { id: 'folk_bass', label: 'Acoustic Bass', styles: ['folk_country_bluegrass'], tags: ['tight_register', 'stable'], instrumentPreset: 'gm:0:32' },
  { id: 'folk_accordion', label: 'Folk Accordion', styles: ['folk_country_bluegrass'], tags: ['warm', 'wide_register'], instrumentPreset: 'gm:0:21' },
  { id: 'folk_woodwinds', label: 'Folk Flute', styles: ['folk_country_bluegrass'], tags: ['airy', 'dreamy'], instrumentPreset: 'gm:0:73' },

  { id: 'legacy_piano', label: 'Legacy Piano', styles: ['legacy'], tags: ['neutral'], instrumentPreset: 'gm:0:0' },
];

export const REGISTER_SUGGESTIONS = [
  { id: 'wide_score', label: 'Wide Score', styles: ['classical_film', 'edm_electronic'], tags: ['wide_register', 'heroic'], min: 40, max: 92 },
  { id: 'mid_ensemble', label: 'Mid Ensemble', styles: ['classical_film', 'jazz_blues_funk'], tags: ['stable', 'bright'], min: 50, max: 86 },
  { id: 'classical_high_strings', label: 'High Strings', styles: ['classical_film'], tags: ['wide_register', 'bright'], min: 60, max: 96 },
  { id: 'classical_low_brass', label: 'Low Brass', styles: ['classical_film'], tags: ['dark', 'tight_register'], min: 36, max: 72 },
  { id: 'classical_chamber', label: 'Chamber Range', styles: ['classical_film'], tags: ['stable', 'tight_register'], min: 55, max: 80 },
  { id: 'classical_high_bells', label: 'High Bells', styles: ['classical_film'], tags: ['sparkle', 'wide_register'], min: 72, max: 98 },
  { id: 'tight_combo', label: 'Tight Combo', styles: ['jazz_blues_funk', 'latin_afro_cuban'], tags: ['tight_register', 'swing'], min: 52, max: 80 },
  { id: 'jazz_low', label: 'Jazz Low', styles: ['jazz_blues_funk'], tags: ['dark', 'tight_register'], min: 40, max: 72 },
  { id: 'jazz_mid', label: 'Jazz Mid', styles: ['jazz_blues_funk'], tags: ['stable', 'bright'], min: 48, max: 82 },
  { id: 'jazz_high', label: 'Jazz High', styles: ['jazz_blues_funk'], tags: ['bright', 'wide_register'], min: 60, max: 90 },
  { id: 'jazz_wide', label: 'Jazz Wide', styles: ['jazz_blues_funk'], tags: ['wide_register', 'dreamy'], min: 45, max: 90 },
  { id: 'rock_stack_register', label: 'Rock Stack', styles: ['pop_rock'], tags: ['heroic', 'high_energy'], min: 48, max: 84 },
  { id: 'rock_low', label: 'Rock Low Crunch', styles: ['pop_rock'], tags: ['dark', 'tight_register'], min: 43, max: 76 },
  { id: 'rock_mid', label: 'Rock Mid', styles: ['pop_rock'], tags: ['bright', 'stable'], min: 50, max: 86 },
  { id: 'rock_high', label: 'Rock High', styles: ['pop_rock'], tags: ['wide_register', 'bright'], min: 62, max: 92 },
  { id: 'rock_wide', label: 'Rock Wide', styles: ['pop_rock'], tags: ['wide_register', 'heroic'], min: 45, max: 94 },
  { id: 'rock_bass', label: 'Rock Bass Focus', styles: ['pop_rock'], tags: ['tight_register', 'dark'], min: 36, max: 68 },
  { id: 'edm_mid', label: 'EDM Mid', styles: ['edm_electronic'], tags: ['on_grid', 'bright'], min: 52, max: 88 },
  { id: 'edm_bass_range', label: 'EDM Bass Focus', styles: ['edm_electronic'], tags: ['dark', 'tension'], min: 36, max: 70 },
  { id: 'edm_wide', label: 'EDM Wide', styles: ['edm_electronic'], tags: ['wide_register', 'bright'], min: 44, max: 96 },
  { id: 'edm_high', label: 'EDM High', styles: ['edm_electronic'], tags: ['sparkle', 'wide_register'], min: 62, max: 94 },
  { id: 'edm_pluck_range', label: 'EDM Pluck Range', styles: ['edm_electronic'], tags: ['bright', 'on_grid'], min: 56, max: 88 },
  { id: 'latin_mid', label: 'Clave Mid', styles: ['latin_afro_cuban'], tags: ['syncopated', 'bright'], min: 55, max: 86 },
  { id: 'latin_wide', label: 'Latin Wide', styles: ['latin_afro_cuban'], tags: ['wide_register', 'ceremonial'], min: 48, max: 90 },
  { id: 'latin_low', label: 'Latin Low', styles: ['latin_afro_cuban'], tags: ['dark', 'tight_register'], min: 45, max: 78 },
  { id: 'latin_high', label: 'Latin High', styles: ['latin_afro_cuban'], tags: ['bright', 'wide_register'], min: 62, max: 92 },
  { id: 'latin_mid_low', label: 'Latin Mid Low', styles: ['latin_afro_cuban'], tags: ['stable', 'percussive'], min: 50, max: 82 },
  { id: 'folk_mid', label: 'Folk Mid', styles: ['folk_country_bluegrass'], tags: ['bright', 'stable'], min: 50, max: 84 },
  { id: 'folk_low', label: 'Folk Low', styles: ['folk_country_bluegrass'], tags: ['dark', 'low_energy'], min: 45, max: 76 },
  { id: 'folk_high', label: 'Folk High', styles: ['folk_country_bluegrass'], tags: ['bright', 'wide_register'], min: 62, max: 90 },
  { id: 'folk_wide', label: 'Folk Wide', styles: ['folk_country_bluegrass'], tags: ['wide_register', 'dreamy'], min: 48, max: 92 },
  { id: 'folk_bass', label: 'Folk Bass', styles: ['folk_country_bluegrass'], tags: ['tight_register', 'stable'], min: 38, max: 70 },
  { id: 'folk_upper', label: 'Folk Upper', styles: ['folk_country_bluegrass'], tags: ['bright', 'stable'], min: 55, max: 86 },
  { id: 'legacy_default_register', label: 'Legacy Default', styles: ['legacy'], tags: ['neutral'], min: 48, max: 84 },
];

export const INSTRUMENT_BY_ID = INSTRUMENT_SUGGESTIONS.reduce((acc, item) => {
  acc[item.id] = item;
  return acc;
}, {});

export const REGISTER_BY_ID = REGISTER_SUGGESTIONS.reduce((acc, item) => {
  acc[item.id] = item;
  return acc;
}, {});
