export const PATTERN_CATALOG = [
  {
    id: 'simple_arpeggio',
    label: 'Simple Arpeggio',
    styles: ['classical_film', 'jazz_blues_funk', 'pop_rock', 'edm_electronic', 'latin_afro_cuban', 'folk_country_bluegrass', 'legacy'],
    tags: ['bright', 'stable', 'on_grid'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'descending_arpeggio',
    label: 'Descending Arpeggio',
    styles: ['classical_film', 'jazz_blues_funk', 'pop_rock', 'edm_electronic', 'latin_afro_cuban', 'folk_country_bluegrass', 'legacy'],
    tags: ['dark', 'dreamy', 'on_grid'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/12',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'skipping_arpeggio',
    label: 'Skipping Arp',
    styles: ['classical_film', 'jazz_blues_funk', 'pop_rock', 'edm_electronic'],
    tags: ['syncopated', 'bright', 'high_energy'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
    requiresCapability: 'gen_broken_chords',
  },
  {
    id: 'alberti_bass',
    label: 'Alberti Bass',
    styles: ['classical_film', 'legacy'],
    tags: ['flowing', 'stable', 'low_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_alberti_bass',
  },
  {
    id: 'sustain_drone',
    label: 'Drone / Sustain',
    styles: ['classical_film', 'edm_electronic', 'folk_country_bluegrass'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/4',
    requiresHarmony: false,
    requiresCapability: 'gen_sustain_basic',
  },
  {
    id: 'offbeat_plucks',
    label: 'Offbeat Plucks',
    styles: ['jazz_blues_funk', 'pop_rock', 'latin_afro_cuban', 'edm_electronic'],
    tags: ['syncopated', 'high_energy', 'bright'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/12',
    requiresHarmony: true,
    requiresCapability: 'gen_offbeat_plucks',
  },
  {
    id: 'swing_response',
    label: 'Swing Response',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'low_energy', 'dreamy'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/12',
    requiresHarmony: true,
    requiresCapability: 'gen_call_response',
  },
  {
    id: 'latin_clave',
    label: 'Clave Stab',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'percussive', 'high_energy'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/12',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'folk_roll',
    label: 'Rolling Strum',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'stable', 'swing'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_sustain_basic',
  },
  {
    id: 'airy_arp',
    label: 'Airy Arp',
    styles: ['classical_film', 'edm_electronic'],
    tags: ['dreamy', 'wide_register', 'bright'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/16',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'grit_riff',
    label: 'Grit Riff',
    styles: ['pop_rock'],
    tags: ['dark', 'high_energy', 'on_grid'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_broken_chords',
  },
  {
    id: 'walking_bass',
    label: 'Walking Bass',
    styles: ['jazz_blues_funk', 'pop_rock'],
    tags: ['swing', 'high_energy', 'tight_register'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_walking_bass',
  },
  {
    id: 'ostinato_pulse',
    label: 'Ostinato Pulse',
    styles: ['classical_film', 'edm_electronic', 'pop_rock'],
    tags: ['tension', 'on_grid', 'high_energy'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
  },
  {
    id: 'walking_bass_simple',
    label: 'Walking Bass (Simple)',
    styles: ['jazz_blues_funk', 'pop_rock'],
    tags: ['swing', 'stable', 'low_register'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/8',
    requiresHarmony: true,
  },
  {
    id: 'comping_stabs',
    label: 'Comping Stabs',
    styles: ['jazz_blues_funk', 'pop_rock'],
    tags: ['syncopated', 'percussive', 'bright'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/12',
    requiresHarmony: true,
  },
  {
    id: 'gate_mask',
    label: 'Gate Mask',
    styles: ['edm_electronic'],
    tags: ['pumping', 'on_grid', 'syncopated'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/16',
    requiresHarmony: false,
  },
  {
    id: 'step_arp_octave',
    label: 'Step Arp Octave',
    styles: ['edm_electronic', 'pop_rock'],
    tags: ['bright', 'on_grid', 'high_energy'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/16',
    requiresHarmony: true,
  },
  {
    id: 'pad_drone',
    label: 'Pad Drone',
    styles: ['classical_film', 'edm_electronic'],
    tags: ['dreamy', 'low_energy', 'wide_register'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/4',
    requiresHarmony: false,
  },
  {
    id: 'pedal_tone',
    label: 'Pedal Tone',
    styles: ['classical_film', 'pop_rock'],
    tags: ['tension', 'low_energy', 'low_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/4',
    requiresHarmony: true,
  },
  {
    id: 'root_pulse',
    label: 'Root Pulse',
    styles: ['pop_rock', 'edm_electronic'],
    tags: ['on_grid', 'stable', 'low_register'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/8',
    requiresHarmony: true,
  },
  {
    id: 'pulse',
    label: 'Pulse',
    styles: ['edm_electronic', 'pop_rock'],
    tags: ['on_grid', 'high_energy', 'tight_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: false,
  },
  {
    id: 'strum_roll',
    label: 'Strum Roll',
    styles: ['folk_country_bluegrass', 'pop_rock'],
    tags: ['bright', 'flowing', 'wide_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/16',
    requiresHarmony: true,
  },
  {
    id: 'riff',
    label: 'Riff',
    styles: ['pop_rock', 'jazz_blues_funk'],
    tags: ['high_energy', 'dark', 'tight_register'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/8',
    requiresHarmony: true,
  },
  {
    id: 'hook',
    label: 'Hook',
    styles: ['pop_rock', 'edm_electronic'],
    tags: ['bright', 'high_energy', 'on_grid'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
  },
  {
    id: 'call_response',
    label: 'Call & Response',
    styles: ['jazz_blues_funk', 'folk_country_bluegrass'],
    tags: ['swing', 'syncopated', 'playful'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/12',
    requiresHarmony: true,
  },
  {
    id: 'chops',
    label: 'Chops',
    styles: ['edm_electronic', 'pop_rock'],
    tags: ['syncopated', 'percussive', 'high_energy'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
  },
  {
    id: 'light_fills',
    label: 'Light Fills',
    styles: ['pop_rock', 'jazz_blues_funk'],
    tags: ['syncopated', 'bright', 'low_energy'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/16',
    requiresHarmony: true,
  },
  {
    id: 'fill_transition',
    label: 'Fill Transition',
    styles: ['pop_rock', 'edm_electronic'],
    tags: ['high_energy', 'tension', 'syncopated'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
  },
  {
    id: 'half_time',
    label: 'Half-Time',
    styles: ['pop_rock', 'edm_electronic'],
    tags: ['low_energy', 'on_grid', 'wide_register'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/4',
    requiresHarmony: true,
  },
  {
    id: 'swing_groove',
    label: 'Swing Groove',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'high_energy', 'syncopated'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/12',
    requiresHarmony: true,
  },
  {
    id: 'busy_groove',
    label: 'Busy Groove',
    styles: ['jazz_blues_funk', 'edm_electronic'],
    tags: ['high_energy', 'syncopated', 'tight_register'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
  },
  {
    id: 'riser',
    label: 'Riser',
    styles: ['edm_electronic'],
    tags: ['tension', 'high_energy', 'wide_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/16',
    requiresHarmony: false,
  },
  {
    id: 'noise_sweep',
    label: 'Noise Sweep',
    styles: ['edm_electronic'],
    tags: ['tension', 'wide_register', 'low_energy'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/8',
    requiresHarmony: false,
  },
  {
    id: 'impact',
    label: 'Impact',
    styles: ['edm_electronic', 'pop_rock'],
    tags: ['percussive', 'high_energy', 'on_grid'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/4',
    requiresHarmony: false,
  },
  {
    id: 'montuno_pattern',
    label: 'Montuno Sketch',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'high_energy', 'percussive'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_montuno',
  },
  {
    id: 'travis_pick',
    label: 'Travis Picking',
    styles: ['folk_country_bluegrass'],
    tags: ['syncopated', 'swing', 'bright'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_travis_picking',
  },
  {
    id: 'string_pulse',
    label: 'String Pulse',
    styles: ['classical_film'],
    tags: ['tension', 'high_energy', 'tight_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'pizzicato_stabs',
    label: 'Pizzicato Stabs',
    styles: ['classical_film'],
    tags: ['bright', 'syncopated', 'tight_register'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
    requiresCapability: 'gen_broken_chords',
  },
  {
    id: 'comping_chords',
    label: 'Comping Chords',
    styles: ['jazz_blues_funk'],
    tags: ['swing', 'stable', 'bright'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/12',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'funk_clav',
    label: 'Funk Clav',
    styles: ['jazz_blues_funk'],
    tags: ['syncopated', 'high_energy', 'bright'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
    requiresCapability: 'gen_offbeat_plucks',
  },
  {
    id: 'anthem_strum',
    label: 'Anthem Strum',
    styles: ['pop_rock'],
    tags: ['bright', 'stable', 'on_grid'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_sustain_basic',
  },
  {
    id: 'power_chords',
    label: 'Power Chords',
    styles: ['pop_rock'],
    tags: ['high_energy', 'tight_register', 'heroic'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_broken_chords',
  },
  {
    id: 'sidechain_pulse',
    label: 'Sidechain Pulse',
    styles: ['edm_electronic'],
    tags: ['on_grid', 'high_energy', 'pumping'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/8',
    requiresHarmony: false,
    requiresCapability: 'gen_sustain_basic',
  },
  {
    id: 'stutter_chops',
    label: 'Stutter Chops',
    styles: ['edm_electronic'],
    tags: ['syncopated', 'bright', 'high_energy'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
    requiresCapability: 'gen_broken_chords',
  },
  {
    id: 'poly_bounce',
    label: 'Poly Bounce',
    styles: ['edm_electronic'],
    tags: ['syncopated', 'tension', 'wide_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/12',
    requiresHarmony: true,
    requiresCapability: 'gen_poly_rhythms',
  },
  {
    id: 'cascara_ticks',
    label: 'Cáscara Ticks',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'percussive', 'on_grid'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/12',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'bongo_rolls',
    label: 'Bongo Rolls',
    styles: ['latin_afro_cuban'],
    tags: ['high_energy', 'percussive', 'syncopated'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/16',
    requiresHarmony: false,
    requiresCapability: 'gen_sustain_basic',
  },
  {
    id: 'tres_guajeo',
    label: 'Tres Guajeo',
    styles: ['latin_afro_cuban'],
    tags: ['syncopated', 'bright', 'high_energy'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_montuno',
  },
  {
    id: 'boom_chuck',
    label: 'Boom-Chuck',
    styles: ['folk_country_bluegrass'],
    tags: ['stable', 'on_grid', 'tight_register'],
    mapsToPatternType: 'arp-3-down',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_sustain_basic',
  },
  {
    id: 'mandolin_chop',
    label: 'Mandolin Chop',
    styles: ['folk_country_bluegrass'],
    tags: ['bright', 'syncopated', 'tight_register'],
    mapsToPatternType: 'arp-3-skip',
    recommendedGrid: '1/16',
    requiresHarmony: true,
    requiresCapability: 'gen_arpeggio_basic',
  },
  {
    id: 'banjo_clawhammer',
    label: 'Banjo Clawhammer',
    styles: ['folk_country_bluegrass'],
    tags: ['high_energy', 'swing', 'tight_register'],
    mapsToPatternType: 'arp-3-up',
    recommendedGrid: '1/8',
    requiresHarmony: true,
    requiresCapability: 'gen_travis_picking',
  },
];

export const NOTE_PATTERNS = PATTERN_CATALOG.map(pattern => ({
  id: pattern.id,
  label: pattern.label,
  patternType: pattern.mapsToPatternType,
}));

export const PATTERN_BY_ID = PATTERN_CATALOG.reduce((acc, pattern) => {
  acc[pattern.id] = pattern;
  return acc;
}, {});

export const NOTE_PATTERN_BY_ID = NOTE_PATTERNS.reduce((acc, pattern) => {
  acc[pattern.id] = pattern;
  return acc;
}, {});

export const FALLBACK_PATTERNS = ['simple_arpeggio', 'sustain_drone'];
