export const PRESET_LIBRARY = [
  {
    id: 'bright-lead-hook',
    name: 'Bright Lead Hook',
    description: 'Upfront lead hook with energetic motion.',
    code: 'MIND|PS2|GV1|role=chorus;voice=lead;style=pop;inst=gm:0:80;pat=hook;mood=bright;energy=high;complexity=normal;variation=fresh;len=8;reg=mid;reroll=1;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=auto;avoid_chromatic=auto;voice_art=accented;voice_tone=bright;voice_human=medium;voice_poly=poly;voice_layer=single;pattern_mask=auto;pattern_density=high;pattern_accents=high;pattern_contour=rising;pattern_repeat=looped;mood_tension=medium;mood_bright=high;mood_resolve=resolved;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=bursts;complexity_harmony=normal;complexity_melody=medium;complexity_rhythm=medium;complexity_orn=low;variation_strategy=mutate;variation_similarity=medium;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=late;register_width=mid;register_move=drift',
  },
  {
    id: 'dreamy-pad-intro',
    name: 'Dreamy Pad Intro',
    description: 'Sparse, warm pad intro with wide register.',
    code: 'MIND|PS2|GV1|role=intro;voice=harmony;style=cinematic;inst=gm:0:48;pat=pad_drone;mood=dreamy;energy=low;complexity=simple;variation=similar;len=8;reg=low;reroll=2;style_sub=classic;style_era=vintage;style_feel=auto;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=avoid;avoid_chromatic=auto;voice_art=legato;voice_tone=soft;voice_human=low;voice_poly=poly;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=looped;mood_tension=low;mood_bright=low;mood_resolve=resolved;energy_dyn=low;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=long;variation_seedmode=locked;length_phrase=stretched;length_cadence=late;register_width=wide;register_move=static',
  },
  {
    id: 'midnight-bass-pulse',
    name: 'Midnight Bass Pulse',
    description: 'Dark, steady bass pulse with low register.',
    code: 'MIND|PS2|GV1|role=verse;voice=bass;style=electronic;inst=gm:0:32;pat=root_pulse;mood=dark;energy=medium;complexity=normal;variation=similar;len=8;reg=low;reroll=3;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=avoid;avoid_leaps=avoid;avoid_busy=auto;avoid_chromatic=auto;voice_art=staccato;voice_tone=neutral;voice_human=low;voice_poly=mono;voice_layer=single;pattern_mask=straight;pattern_density=medium;pattern_accents=medium;pattern_contour=flat;pattern_repeat=looped;mood_tension=medium;mood_bright=low;mood_resolve=open;energy_dyn=medium;energy_drive=medium;energy_attack=medium;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=medium;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=medium;variation_seedmode=locked;length_phrase=balanced;length_cadence=late;register_width=narrow;register_move=static',
  },
  {
    id: 'swinging-drums',
    name: 'Swinging Drums',
    description: 'Jazz-inspired swing groove with soft dynamics.',
    code: 'MIND|PS2|GV1|role=verse;voice=drums;style=jazz;inst=gm_hat;pat=swing_groove;mood=warm;energy=medium;complexity=normal;variation=similar;len=8;reg=mid;reroll=4;style_sub=classic;style_era=vintage;style_feel=swing;avoid_arps=auto;avoid_leaps=auto;avoid_busy=auto;avoid_chromatic=auto;voice_art=auto;voice_tone=soft;voice_human=medium;voice_poly=auto;voice_layer=single;pattern_mask=syncopated;pattern_density=medium;pattern_accents=medium;pattern_contour=flat;pattern_repeat=looped;mood_tension=low;mood_bright=medium;mood_resolve=resolved;energy_dyn=medium;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=medium;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=medium;variation_seedmode=locked;length_phrase=balanced;length_cadence=center;register_width=mid;register_move=static',
  },
  {
    id: 'anthem-chorus-strum',
    name: 'Anthem Chorus Strum',
    description: 'Big rock strums for chorus lift.',
    code: 'MIND|PS2|GV1|role=chorus;voice=harmony;style=rock;inst=gm:0:24;pat=strum_roll;mood=epic;energy=high;complexity=normal;variation=fresh;len=8;reg=mid;reroll=5;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=auto;avoid_chromatic=auto;voice_art=accented;voice_tone=bright;voice_human=medium;voice_poly=poly;voice_layer=double;pattern_mask=straight;pattern_density=high;pattern_accents=high;pattern_contour=rising;pattern_repeat=looped;mood_tension=medium;mood_bright=high;mood_resolve=resolved;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=bursts;complexity_harmony=normal;complexity_melody=low;complexity_rhythm=medium;complexity_orn=low;variation_strategy=mutate;variation_similarity=medium;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=late;register_width=wide;register_move=drift',
  },
  {
    id: 'lofi-chill-keys',
    name: 'Lo-Fi Chill Keys',
    description: 'Warm, mellow keys with light motion.',
    code: 'MIND|PS2|GV1|role=verse;voice=harmony;style=lo-fi;inst=gm:0:0;pat=pad_drone;mood=warm;energy=low;complexity=simple;variation=similar;len=8;reg=mid;reroll=6;style_sub=classic;style_era=vintage;style_feel=straight;avoid_arps=avoid;avoid_leaps=avoid;avoid_busy=avoid;avoid_chromatic=auto;voice_art=legato;voice_tone=soft;voice_human=medium;voice_poly=poly;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=looped;mood_tension=low;mood_bright=low;mood_resolve=resolved;energy_dyn=low;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=long;variation_seedmode=locked;length_phrase=balanced;length_cadence=late;register_width=mid;register_move=static',
  },
  {
    id: 'trap-hats',
    name: 'Trap Hats',
    description: 'Fast hi-hat pattern with sharp accents.',
    code: 'MIND|PS2|GV1|role=chorus;voice=drums;style=hip-hop;inst=gm_hat;pat=busy_groove;mood=tense;energy=high;complexity=rich;variation=fresh;len=8;reg=high;reroll=7;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=auto;avoid_leaps=auto;avoid_busy=allow;avoid_chromatic=auto;voice_art=accented;voice_tone=bright;voice_human=low;voice_poly=auto;voice_layer=single;pattern_mask=syncopated;pattern_density=high;pattern_accents=high;pattern_contour=rising;pattern_repeat=evolving;mood_tension=high;mood_bright=medium;mood_resolve=open;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=bursts;complexity_harmony=low;complexity_melody=low;complexity_rhythm=high;complexity_orn=medium;variation_strategy=mutate;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=late;register_width=narrow;register_move=drift',
  },
  {
    id: 'cinematic-rise',
    name: 'Cinematic Rise',
    description: 'FX riser for builds and transitions.',
    code: 'MIND|PS2|GV1|role=pre-chorus;voice=fx;style=cinematic;inst=gm:0:52;pat=riser;mood=epic;energy=high;complexity=normal;variation=fresh;len=4;reg=high;reroll=8;style_sub=classic;style_era=modern;style_feel=straight;avoid_arps=auto;avoid_leaps=auto;avoid_busy=auto;avoid_chromatic=auto;voice_art=legato;voice_tone=bright;voice_human=low;voice_poly=auto;voice_layer=single;pattern_mask=auto;pattern_density=medium;pattern_accents=medium;pattern_contour=rising;pattern_repeat=evolving;mood_tension=high;mood_bright=high;mood_resolve=open;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=waves;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=contrast;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=tight;length_cadence=late;register_width=wide;register_move=sweep',
  },
  {
    id: 'bridge-contrast',
    name: 'Bridge Contrast',
    description: 'Contrasting bridge with fresh movement.',
    code: 'MIND|PS2|GV1|role=bridge;voice=lead;style=experimental;inst=gm:0:56;pat=call_response;mood=mysterious;energy=medium;complexity=rich;variation=wild;len=8;reg=mid;reroll=9;style_sub=hybrid;style_era=future;style_feel=auto;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=allow;avoid_chromatic=allow;voice_art=accented;voice_tone=neutral;voice_human=high;voice_poly=poly;voice_layer=double;pattern_mask=syncopated;pattern_density=medium;pattern_accents=high;pattern_contour=falling;pattern_repeat=staggered;mood_tension=high;mood_bright=medium;mood_resolve=suspended;energy_dyn=medium;energy_drive=medium;energy_attack=medium;energy_peaks=waves;complexity_harmony=high;complexity_melody=high;complexity_rhythm=medium;complexity_orn=medium;variation_strategy=contrast;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=center;register_width=mid;register_move=drift',
  },
  {
    id: 'outro-resolve',
    name: 'Outro Resolve',
    description: 'Warm resolution to close the song.',
    code: 'MIND|PS2|GV1|role=outro;voice=harmony;style=classical;inst=gm:0:48;pat=pad_drone;mood=warm;energy=low;complexity=simple;variation=similar;len=8;reg=mid;reroll=10;style_sub=classic;style_era=vintage;style_feel=straight;avoid_arps=avoid;avoid_leaps=avoid;avoid_busy=avoid;avoid_chromatic=auto;voice_art=legato;voice_tone=soft;voice_human=low;voice_poly=poly;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=looped;mood_tension=low;mood_bright=low;mood_resolve=resolved;energy_dyn=low;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=long;variation_seedmode=locked;length_phrase=stretched;length_cadence=late;register_width=wide;register_move=static',
  },
  {
    id: 'fill-transition',
    name: 'Fill Transition',
    description: 'Short transition fill with tight energy.',
    code: 'MIND|PS2|GV1|role=fill;voice=drums;style=pop;inst=gm_snare;pat=fill_transition;mood=tense;energy=high;complexity=rich;variation=fresh;len=2;reg=mid;reroll=11;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=auto;avoid_leaps=auto;avoid_busy=allow;avoid_chromatic=auto;voice_art=accented;voice_tone=bright;voice_human=low;voice_poly=auto;voice_layer=single;pattern_mask=syncopated;pattern_density=high;pattern_accents=high;pattern_contour=flat;pattern_repeat=staggered;mood_tension=high;mood_bright=medium;mood_resolve=open;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=bursts;complexity_harmony=low;complexity_melody=low;complexity_rhythm=high;complexity_orn=medium;variation_strategy=mutate;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=tight;length_cadence=late;register_width=mid;register_move=drift',
  },
  {
    id: 'classic-jazz-walk',
    name: 'Classic Jazz Walk',
    description: 'Walking bass with swing feel.',
    code: 'MIND|PS2|GV1|role=verse;voice=bass;style=jazz;inst=gm:0:32;pat=walking_bass;mood=warm;energy=medium;complexity=normal;variation=similar;len=8;reg=low;reroll=12;style_sub=classic;style_era=vintage;style_feel=swing;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=auto;avoid_chromatic=auto;voice_art=legato;voice_tone=neutral;voice_human=medium;voice_poly=mono;voice_layer=single;pattern_mask=syncopated;pattern_density=medium;pattern_accents=medium;pattern_contour=rising;pattern_repeat=looped;mood_tension=medium;mood_bright=medium;mood_resolve=resolved;energy_dyn=medium;energy_drive=medium;energy_attack=medium;energy_peaks=steady;complexity_harmony=medium;complexity_melody=low;complexity_rhythm=medium;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=medium;variation_seedmode=locked;length_phrase=balanced;length_cadence=center;register_width=narrow;register_move=static',
  },
  {
    id: 'edm-pluck-drive',
    name: 'EDM Pluck Drive',
    description: 'Bright pluck motion for energetic builds.',
    code: 'MIND|PS2|GV1|role=pre-chorus;voice=lead;style=electronic;inst=gm:0:80;pat=riff;mood=bright;energy=high;complexity=normal;variation=fresh;len=8;reg=high;reroll=13;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=allow;avoid_chromatic=auto;voice_art=staccato;voice_tone=bright;voice_human=low;voice_poly=poly;voice_layer=single;pattern_mask=syncopated;pattern_density=high;pattern_accents=high;pattern_contour=rising;pattern_repeat=evolving;mood_tension=medium;mood_bright=high;mood_resolve=open;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=waves;complexity_harmony=normal;complexity_melody=medium;complexity_rhythm=high;complexity_orn=medium;variation_strategy=mutate;variation_similarity=medium;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=late;register_width=mid;register_move=drift',
  },
  {
    id: 'folk-roll',
    name: 'Folk Roll',
    description: 'Strummed roll for folk textures.',
    code: 'MIND|PS2|GV1|role=verse;voice=harmony;style=world;inst=gm:0:24;pat=strum_roll;mood=bright;energy=medium;complexity=normal;variation=similar;len=8;reg=mid;reroll=14;style_sub=classic;style_era=vintage;style_feel=shuffle;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=auto;avoid_chromatic=auto;voice_art=accented;voice_tone=neutral;voice_human=medium;voice_poly=poly;voice_layer=single;pattern_mask=straight;pattern_density=medium;pattern_accents=medium;pattern_contour=flat;pattern_repeat=looped;mood_tension=low;mood_bright=high;mood_resolve=resolved;energy_dyn=medium;energy_drive=medium;energy_attack=medium;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=medium;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=medium;variation_seedmode=locked;length_phrase=balanced;length_cadence=late;register_width=mid;register_move=static',
  },
  {
    id: 'sparse-fx-sweep',
    name: 'Sparse FX Sweep',
    description: 'Noise sweep for subtle transitions.',
    code: 'MIND|PS2|GV1|role=fill;voice=fx;style=cinematic;inst=gm:0:52;pat=noise_sweep;mood=mysterious;energy=medium;complexity=simple;variation=fresh;len=2;reg=high;reroll=15;style_sub=classic;style_era=current;style_feel=auto;avoid_arps=auto;avoid_leaps=auto;avoid_busy=auto;avoid_chromatic=auto;voice_art=legato;voice_tone=soft;voice_human=low;voice_poly=auto;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=staggered;mood_tension=medium;mood_bright=low;mood_resolve=open;energy_dyn=medium;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=contrast;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=tight;length_cadence=late;register_width=wide;register_move=sweep',
  },
  {
    id: 'playful-call-response',
    name: 'Playful Call/Response',
    description: 'Bouncy melodic call and response.',
    code: 'MIND|PS2|GV1|role=verse;voice=lead;style=pop;inst=gm:0:80;pat=call_response;mood=playful;energy=medium;complexity=normal;variation=fresh;len=8;reg=mid;reroll=16;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=allow;avoid_chromatic=auto;voice_art=accented;voice_tone=bright;voice_human=medium;voice_poly=poly;voice_layer=single;pattern_mask=syncopated;pattern_density=medium;pattern_accents=medium;pattern_contour=rising;pattern_repeat=evolving;mood_tension=low;mood_bright=high;mood_resolve=resolved;energy_dyn=medium;energy_drive=medium;energy_attack=medium;energy_peaks=waves;complexity_harmony=normal;complexity_melody=medium;complexity_rhythm=medium;complexity_orn=low;variation_strategy=mutate;variation_similarity=medium;variation_window=medium;variation_seedmode=reroll;length_phrase=balanced;length_cadence=center;register_width=mid;register_move=drift',
  },
  {
    id: 'epic-strings-pulse',
    name: 'Epic Strings Pulse',
    description: 'Driving string pulse for cinematic energy.',
    code: 'MIND|PS2|GV1|role=chorus;voice=harmony;style=cinematic;inst=gm:0:48;pat=pulse;mood=epic;energy=high;complexity=normal;variation=fresh;len=8;reg=mid;reroll=17;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=auto;avoid_chromatic=auto;voice_art=accented;voice_tone=bright;voice_human=low;voice_poly=poly;voice_layer=double;pattern_mask=straight;pattern_density=high;pattern_accents=high;pattern_contour=rising;pattern_repeat=looped;mood_tension=medium;mood_bright=high;mood_resolve=resolved;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=bursts;complexity_harmony=normal;complexity_melody=low;complexity_rhythm=medium;complexity_orn=low;variation_strategy=mutate;variation_similarity=medium;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=late;register_width=wide;register_move=drift',
  },
  {
    id: 'dark-drone',
    name: 'Dark Drone',
    description: 'Low, tense drone for suspense.',
    code: 'MIND|PS2|GV1|role=intro;voice=harmony;style=cinematic;inst=gm:0:48;pat=pad_drone;mood=dark;energy=low;complexity=simple;variation=similar;len=8;reg=low;reroll=18;style_sub=classic;style_era=vintage;style_feel=auto;avoid_arps=avoid;avoid_leaps=avoid;avoid_busy=avoid;avoid_chromatic=auto;voice_art=legato;voice_tone=neutral;voice_human=low;voice_poly=poly;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=looped;mood_tension=high;mood_bright=low;mood_resolve=suspended;energy_dyn=low;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=long;variation_seedmode=locked;length_phrase=stretched;length_cadence=late;register_width=wide;register_move=static',
  },
  {
    id: 'warm-choir-bridge',
    name: 'Warm Choir Bridge',
    description: 'Warm choir texture for bridge contrast.',
    code: 'MIND|PS2|GV1|role=bridge;voice=harmony;style=classical;inst=gm:0:52;pat=pad_drone;mood=warm;energy=medium;complexity=normal;variation=fresh;len=8;reg=mid;reroll=19;style_sub=classic;style_era=vintage;style_feel=straight;avoid_arps=avoid;avoid_leaps=avoid;avoid_busy=avoid;avoid_chromatic=auto;voice_art=legato;voice_tone=soft;voice_human=medium;voice_poly=poly;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=looped;mood_tension=low;mood_bright=medium;mood_resolve=resolved;energy_dyn=medium;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=normal;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=mutate;variation_similarity=medium;variation_window=medium;variation_seedmode=reroll;length_phrase=balanced;length_cadence=center;register_width=mid;register_move=static',
  },
  {
    id: 'percussive-chops',
    name: 'Percussive Chops',
    description: 'Chopped harmony accents with bite.',
    code: 'MIND|PS2|GV1|role=chorus;voice=harmony;style=electronic;inst=gm:0:0;pat=chops;mood=tense;energy=high;complexity=normal;variation=fresh;len=8;reg=mid;reroll=20;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=avoid;avoid_leaps=allow;avoid_busy=allow;avoid_chromatic=auto;voice_art=staccato;voice_tone=bright;voice_human=low;voice_poly=poly;voice_layer=double;pattern_mask=syncopated;pattern_density=high;pattern_accents=high;pattern_contour=flat;pattern_repeat=evolving;mood_tension=high;mood_bright=medium;mood_resolve=open;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=bursts;complexity_harmony=normal;complexity_melody=low;complexity_rhythm=high;complexity_orn=medium;variation_strategy=mutate;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=late;register_width=mid;register_move=drift',
  },
  {
    id: 'ambient-world-pad',
    name: 'Ambient World Pad',
    description: 'Soft world texture with gentle motion.',
    code: 'MIND|PS2|GV1|role=verse;voice=harmony;style=world;inst=gm:0:48;pat=pad_drone;mood=dreamy;energy=low;complexity=simple;variation=similar;len=8;reg=mid;reroll=21;style_sub=classic;style_era=vintage;style_feel=auto;avoid_arps=avoid;avoid_leaps=avoid;avoid_busy=avoid;avoid_chromatic=auto;voice_art=legato;voice_tone=soft;voice_human=medium;voice_poly=poly;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=looped;mood_tension=low;mood_bright=medium;mood_resolve=resolved;energy_dyn=low;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=long;variation_seedmode=locked;length_phrase=balanced;length_cadence=late;register_width=wide;register_move=static',
  },
  {
    id: 'energy-build-drums',
    name: 'Energy Build Drums',
    description: 'Half-time build for pre-chorus.',
    code: 'MIND|PS2|GV1|role=pre-chorus;voice=drums;style=rock;inst=gm_snare;pat=half_time;mood=tense;energy=high;complexity=normal;variation=fresh;len=8;reg=mid;reroll=22;style_sub=modern;style_era=current;style_feel=straight;avoid_arps=auto;avoid_leaps=auto;avoid_busy=allow;avoid_chromatic=auto;voice_art=accented;voice_tone=bright;voice_human=low;voice_poly=auto;voice_layer=single;pattern_mask=straight;pattern_density=medium;pattern_accents=high;pattern_contour=rising;pattern_repeat=evolving;mood_tension=high;mood_bright=medium;mood_resolve=open;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=waves;complexity_harmony=low;complexity_melody=low;complexity_rhythm=medium;complexity_orn=low;variation_strategy=mutate;variation_similarity=medium;variation_window=short;variation_seedmode=reroll;length_phrase=balanced;length_cadence=late;register_width=mid;register_move=drift',
  },
  {
    id: 'minimal-bass-pedal',
    name: 'Minimal Bass Pedal',
    description: 'Pedal tone bass for slow builds.',
    code: 'MIND|PS2|GV1|role=intro;voice=bass;style=cinematic;inst=gm:0:32;pat=pedal_tone;mood=mysterious;energy=low;complexity=simple;variation=similar;len=8;reg=low;reroll=23;style_sub=classic;style_era=vintage;style_feel=auto;avoid_arps=avoid;avoid_leaps=avoid;avoid_busy=avoid;avoid_chromatic=auto;voice_art=legato;voice_tone=neutral;voice_human=low;voice_poly=mono;voice_layer=single;pattern_mask=sparse;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=looped;mood_tension=medium;mood_bright=low;mood_resolve=open;energy_dyn=low;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=repeat;variation_similarity=high;variation_window=long;variation_seedmode=locked;length_phrase=balanced;length_cadence=late;register_width=narrow;register_move=static',
  },
  {
    id: 'wild-experimental-lead',
    name: 'Wild Experimental Lead',
    description: 'Unpredictable lead texture for experimentation.',
    code: 'MIND|PS2|GV1|role=bridge;voice=lead;style=experimental;inst=gm:0:80;pat=light_fills;mood=mysterious;energy=high;complexity=rich;variation=wild;len=8;reg=high;reroll=24;style_sub=hybrid;style_era=future;style_feel=auto;avoid_arps=allow;avoid_leaps=allow;avoid_busy=allow;avoid_chromatic=allow;voice_art=accented;voice_tone=bright;voice_human=high;voice_poly=poly;voice_layer=double;pattern_mask=syncopated;pattern_density=high;pattern_accents=high;pattern_contour=falling;pattern_repeat=staggered;mood_tension=high;mood_bright=medium;mood_resolve=suspended;energy_dyn=high;energy_drive=high;energy_attack=high;energy_peaks=bursts;complexity_harmony=high;complexity_melody=high;complexity_rhythm=high;complexity_orn=high;variation_strategy=contrast;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=stretched;length_cadence=late;register_width=wide;register_move=sweep',
  },
  {
    id: 'chilled-fx-impact',
    name: 'Chilled FX Impact',
    description: 'Soft impact for transitions.',
    code: 'MIND|PS2|GV1|role=fill;voice=fx;style=lo-fi;inst=gm:0:52;pat=impact;mood=warm;energy=medium;complexity=simple;variation=fresh;len=2;reg=mid;reroll=25;style_sub=classic;style_era=vintage;style_feel=auto;avoid_arps=auto;avoid_leaps=auto;avoid_busy=auto;avoid_chromatic=auto;voice_art=legato;voice_tone=soft;voice_human=low;voice_poly=auto;voice_layer=single;pattern_mask=auto;pattern_density=low;pattern_accents=low;pattern_contour=flat;pattern_repeat=staggered;mood_tension=low;mood_bright=medium;mood_resolve=resolved;energy_dyn=medium;energy_drive=low;energy_attack=low;energy_peaks=steady;complexity_harmony=low;complexity_melody=low;complexity_rhythm=low;complexity_orn=low;variation_strategy=contrast;variation_similarity=low;variation_window=short;variation_seedmode=reroll;length_phrase=tight;length_cadence=late;register_width=mid;register_move=static',
  },
];
